services:
  redis:
    image: redis:alpine
  api:
    build: ./api
    ports: 
      - "8000:5000"
    environment:
      - REDIS_HOST=redis
      - PYTHONUNBUFFERED=1
    depends_on:
      - redis
  worker:
    build: ./worker
    environment:
      - REDIS_HOST=redis
      - PYTHONUNBUFFERED=1
    depends_on: 
      - redis
  jenkins:
    build: ./jenkins
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ${HOME}/.kube/config.jenkins:/var/jenkins_home/.kube/config:ro
    networks:
      - default
      - kind
volumes:
  jenkins_home:
networks:
  kind:
    external: true
